"""profile avatar theme aliases email changes

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 08:08:42.526001
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_changes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('username_aliases',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_username_aliases_user_id'), 'username_aliases', ['user_id'], unique=False)
    op.add_column('users', sa.Column('avatar', sa.String(length=32), server_default='cat', nullable=False))
    op.add_column('users', sa.Column('theme', sa.String(length=8), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    op.drop_column('users', 'avatar')
    op.drop_index(op.f('ix_username_aliases_user_id'), table_name='username_aliases')
    op.drop_table('username_aliases')
    op.drop_table('email_changes')
    # ### end Alembic commands ###
