"""link schedule and password

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 06:57:15.708624
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('links', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'password_hash')
    op.drop_column('links', 'starts_at')
    # ### end Alembic commands ###
